kind: Namespace
apiVersion: v1
metadata:
  name: tenant1
  labels:
    name: tenant1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-kubernetes-tenant1
  namespace: tenant1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-kubernetes-tenant1
  template:
    metadata:
      labels:
        app: hello-kubernetes-tenant1
    spec:
      containers:
        - name: hello-kubernetes
          image: paulbouwer/hello-kubernetes:1.7
          ports:
            - containerPort: 8080
          env:
            - name: MESSAGE
              value: Hello from the fourth deployment!
---
apiVersion: v1
kind: Service
metadata:
  name: hello-kubernetes-tenant1
  namespace: tenant1
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: hello-kubernetes-tenant1
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: hello-kubernetes-ingress-tenant1
  namespace: tenant1
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-production"
spec:
  tls:
    - hosts:
        - tenant1.membermatters.co
        - tenant1a.membermatters.co
      secretName: echo-tls
  rules:
    - host: tenant1.membermatters.co
      http:
        paths:
          - backend:
              serviceName: hello-kubernetes-tenant1
              servicePort: 80
    - host: tenant1a.membermatters.co
      http:
        paths:
          - backend:
              serviceName: hello-kubernetes-tenant1
              servicePort: 80